# Generated by Django 2.2.2 on 2019-06-22 01:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import skippedia.skippedia.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nim', models.CharField(max_length=8)),
                ('jurusan', models.CharField(choices=[('IF', 'Teknik Informatika'), ('STI', 'Sistem dan Teknologi Informasi')], default='IF', max_length=3)),
                ('angkatan', models.PositiveIntegerField(default=2019, validators=[django.core.validators.MinValueValidator(1984), skippedia.skippedia.models.max_value_current_year])),
                ('photo', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nim',),
            },
        ),
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', skippedia.skippedia.models.IntegerRangeField()),
                ('comment', models.CharField(max_length=255)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reputations', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sended_reputations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
