# Generated by Django 2.2.2 on 2019-06-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skippedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.CharField(blank=True, default='default.jpg', max_length=255),
        ),
    ]
