# Generated by Django 2.2.2 on 2019-06-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skippedia', '0002_auto_20190622_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(default='19bc4bf2-d4c5-460e-8175-d56fc92d129b', max_length=255, primary_key=True, serialize=False),
        ),
    ]
